### PR TITLE
Fixes #25

### LINKED ISSUE #25: wget2 compatibility issues
As an opera user, I've been using this fix for a while now, and I encountered an issue... There was a similar error in a previous issue, but seems like the cause may be different?

image

I managed to fix it by piping it to `jq`.

But then afterwards, I ran into another problem with `wget`

image

seems like this is an issue with different `wget` versions.

### PR DESCRIPTION
**Pull request by FishyW**
Here's my proposal to fix #25, although this requires an extra package `jq` so maybe there's a better fix...

### CODE REVIEW

**Comment by Ld-Hagen** [comment]
Output of 
`wget -q4O - https://api.github.com/repos/Ld-Hagen/nwjs-ffmpeg-prebuilt/releases | jq | grep browser_download_url | cut -d '"' -f 4 | grep linux-x64 | head -n 1`
and 
wget -q4O - https://api.github.com/repos/Ld-Hagen/nwjs-ffmpeg-prebuilt/releases | grep browser_download_url | cut -d '"' -f 4 | grep linux-x64 | head -n 1
shouldn't be different. Check it again? probably there were some network issues.

Anyway, using jq is reasonable but in more useful form
`wget -q4O - https://api.github.com/repos/Ld-Hagen/nwjs-ffmpeg-prebuilt/releases | jq -r '.[0].assets[0].browser_download_url'`

**Comment by Ld-Hagen** [comment]
Also wget with -q option won't output anything without --show-progress.
But --show-progress option is replaced with --force-progress in wget2

So there 2 ways I see:
- to add version check for wget
- completely replace it with curl

**Comment by FishyW** [comment]
> Output of `wget -q4O - https://api.github.com/repos/Ld-Hagen/nwjs-ffmpeg-prebuilt/releases | jq | grep browser_download_url | cut -d '"' -f 4 | grep linux-x64 | head -n 1` and wget -q4O - https://api.github.com/repos/Ld-Hagen/nwjs-ffmpeg-prebuilt/releases | grep browser_download_url | cut -d '"' -f 4 | grep linux-x64 | head -n 1 shouldn't be different. Check it again? probably there were some network issues.
> 
> Anyway, using jq is reasonable but in more useful form `wget -q4O - https://api.github.com/repos/Ld-Hagen/nwjs-ffmpeg-prebuilt/releases | jq -r '.[0].assets[0].browser_download_url'`

image

It's different in my pc here^. Running the `wget` command prints everything in one line, and I think that's the issue (maybe since I'm using a different version of `wget`.)

image

**Comment by FishyW** [comment]
> Also wget with -q option won't output anything without --show-progress. But --show-progress option is replaced with --force-progress in wget2
> 
> So there 2 ways I see:
> 
> * to add version check for wget
> * completely replace it with curl

image

The man page seems to recommend doing `--progress=bar:force:noscroll` for better wget "compatibility". I don't know if that shows the progress bar for `wget` 1.

**Pull request merged**
